"""Target-sweep animation: the gaze cycles through the centre + 4 cardinal midpoints.

Left: the 3D scene. Right: the camera view (pupil + glint) on top, and the matching
per-gaze code snippet below it (generated by code_images.py), in sync with the gaze.

Output: ../img/pupil_glint.mp4
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.gridspec as gridspec
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.patches import Rectangle
from tqdm import tqdm

from pyetsimul.core import Camera, Eye, Light
from pyetsimul.types import Position3D
from pyetsimul.visualization import plot_setup_and_camera_view

from lab_setup import REF_BOUNDS, SWEEP_TARGETS, VIEW_AZIM, VIEW_ELEV, build_camera, build_eyes, build_light

OUT_PATH = Path(__file__).parent.parent / "img" / "pupil_glint.mp4"
CODE_DIR = Path(__file__).parent.parent / "img" / "code"  # per-gaze code images, one per sweep target

CAMERA_CROP_MARGIN = 0.05  # padding around the camera-view feature box

FPS = 30
SECONDS_PER_TARGET = 1.5
FRAMES_PER_TARGET = int(SECONDS_PER_TARGET * FPS)
TOTAL_FRAMES = len(SWEEP_TARGETS) * FRAMES_PER_TARGET

PROGRESS_BG = "#eeeeee"
PROGRESS_FG = "#999999"


def _compute_feature_bounds(
    eyes: list[Eye],
    camera: Camera,
    light: Light,
    targets: list[Position3D],
) -> tuple[float, float, float, float]:
    """Find the bounding box of all 2D features across the full target sweep."""
    xs: list[float] = []
    ys: list[float] = []
    for target in targets:
        for eye in eyes:
            eye.look_at(target)
            image = camera.take_image(eye, [light])
            for pt in [image.pupil_center] + (image.pupil_boundary or []) + list(image.corneal_reflections):
                if pt is not None:
                    xs.append(pt.x)
                    ys.append(pt.y)
    return min(xs), max(xs), min(ys), max(ys)


def _apply_crop(ax: plt.Axes, xlim: tuple[float, float], ylim: tuple[float, float]) -> None:
    """Set the camera-view limits; Y flipped so 0 is at the bottom."""
    cur_xlim = ax.get_xlim()
    ax.set_xlim(xlim if cur_xlim[0] < cur_xlim[1] else (xlim[1], xlim[0]))
    ax.set_ylim(min(ylim), max(ylim))  # Y flipped


def main() -> None:
    """Render the target sweep MP4 with the synced per-gaze code below the camera view."""
    eyes = build_eyes()
    camera = build_camera(eyes)
    light = build_light()
    code_imgs = [mpimg.imread(CODE_DIR / f"demo_gaze_{i}.png") for i in range(len(SWEEP_TARGETS))]

    xmin, xmax, ymin, ymax = _compute_feature_bounds(eyes, camera, light, SWEEP_TARGETS)
    x_margin = (xmax - xmin) * CAMERA_CROP_MARGIN
    y_margin = (ymax - ymin) * CAMERA_CROP_MARGIN
    crop_xlim = (xmin - x_margin, xmax + x_margin)
    crop_ylim = (ymin - y_margin, ymax + y_margin)

    fig = plt.figure(figsize=(16, 9))
    gs = gridspec.GridSpec(
        2,
        2,
        height_ratios=[40, 48],
        left=0.04,
        right=0.99,
        top=0.95,
        bottom=0.07,
        wspace=0.12,
        hspace=0.25,
        figure=fig,
    )
    ax_scene = fig.add_subplot(gs[:, 0], projection="3d")  # 3D scene, full left height
    ax_cam = fig.add_subplot(gs[0, 1])  # camera view (top right)
    ax_code = fig.add_subplot(gs[1, 1])  # synced code (bottom right)
    ax_prog = fig.add_axes((0.04, 0.1, 0.95, 0.02))  # thin progress bar; raise this y to move it up
    ax_prog.set_xlim(0, 1)
    ax_prog.set_ylim(0, 1)
    ax_prog.set_xticks([])
    ax_prog.set_yticks([])
    for spine in ax_prog.spines.values():
        spine.set_visible(False)
    ax_prog.add_patch(Rectangle((0, 0), 1, 1, facecolor=PROGRESS_BG))
    prog_bar = ax_prog.add_patch(Rectangle((0, 0), 0, 1, facecolor=PROGRESS_FG))

    def update(frame_idx: int) -> list[Rectangle]:
        target_idx = frame_idx // FRAMES_PER_TARGET
        target = SWEEP_TARGETS[target_idx]
        for eye in eyes:
            eye.look_at(target)
        ax_scene.clear()
        ax_cam.clear()
        ax_code.clear()
        plot_setup_and_camera_view(
            eyes,
            [target] * len(eyes),
            camera,
            [light],
            ax1=ax_scene,
            ax2=ax_cam,
            fig=fig,
            ref_bounds=REF_BOUNDS,
        )
        ax_scene.view_init(elev=VIEW_ELEV, azim=VIEW_AZIM)
        _apply_crop(ax_cam, crop_xlim, crop_ylim)
        ax_cam.set_anchor("S")  # camera image hugs the bottom of its cell
        ax_code.imshow(code_imgs[target_idx])
        ax_code.axis("off")
        ax_code.set_anchor("N")  # code image hugs the top of its cell
        prog_bar.set_width((frame_idx + 1) / TOTAL_FRAMES)
        return [prog_bar]

    anim = FuncAnimation(fig, update, frames=TOTAL_FRAMES, interval=1000 / FPS, blit=False)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with tqdm(total=TOTAL_FRAMES, desc=OUT_PATH.name) as bar:
        anim.save(OUT_PATH, writer="ffmpeg", fps=FPS, dpi=100, progress_callback=lambda *_: bar.update())
    plt.close(fig)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
